pipeshub-ai/pipeshub-ai

frontend/src/sections/knowledgebase/record-details.tsx, frontend/src/sections/qna/chatbot/components/chat-message.tsx, frontend/src/sections/qna/chatbot/components/docx-highlighter.tsx, frontend/src/sections/qna/chatbot/components/highlighter-sidebar.tsx, frontend/src/sections/qna/chatbot/components/html-highlighter.tsx, frontend/src/sections/qna/chatbot/components/markdown-highlighter.tsx, frontend/src/sections/qna/chatbot/components/record-details.tsx, frontend/src/sections/qna/chatbot/components/text-highlighter.tsx
Null checks added for extension, tooltip added for confidence score, page number removed from docx, text, html and markdown type of files
=> Null checks added for extension, tooltip added for confidence score, page number removed from docx, text, html and markdown type of files

services/python/app/config/ai_models_named_constants.py, services/python/app/connectors/api/router.py, services/python/app/connectors/google/admin/google_admin_service.py, services/python/app/connectors/google/core/arango_service.py, services/python/app/connectors/google/core/sync_tasks.py, services/python/app/connectors/google/gmail/core/gmail_user_service.py, services/python/app/connectors/google/gmail/core/sync_service.py, services/python/app/connectors/google/gmail/handlers/change_handler.py, services/python/app/connectors/google/gmail/handlers/webhook_handler.py, services/python/app/connectors/google/google_drive/core/drive_user_service.py, services/python/app/connectors/google/google_drive/core/sync_service.py, services/python/app/connectors/google/google_drive/handlers/change_handler.py, services/python/app/connectors/google/google_drive/handlers/webhook_handler.py, services/python/app/connectors_main.py, services/python/app/events/processor.py, services/python/app/modules/parsers/pdf/pymupdf_ocrmypdf_processor.py, services/python/app/services/kafka_consumer.py, services/python/app/setups/connector_setup.py
=> stream record changes. restart reenable fixes. watch improvements

services/python/app/config/ai_models_named_constants.py, services/python/app/connectors/api/router.py, services/python/app/connectors/google/admin/google_admin_service.py, services/python/app/connectors/google/gmail/core/sync_service.py, services/python/app/connectors/google/google_drive/handlers/webhook_handler.py, services/python/app/core/embedding_service.py, services/python/app/events/events.py, services/python/app/events/processor.py, services/python/app/modules/extraction/prompt_template.py, services/python/app/modules/indexing/run.py, services/python/app/modules/parsers/docx/docparser.py, services/python/app/modules/parsers/excel/xls_parser.py, services/python/app/modules/parsers/pptx/ppt_parser.py, services/python/app/modules/qna/prompt_templates.py, services/python/app/modules/retrieval/retrieval_service.py, services/python/app/services/ai_config_handler.py, services/python/app/services/kafka_consumer.py, services/python/app/setups/indexing_setup.py, services/python/app/setups/query_setup.py, services/python/app/utils/embeddings.py
fixes
retrieval service changes, download changes
gemini suggestions
=> embedding models, timeout and temp file cleanup, other fixes

services/python/app/connectors/api/router.py, services/python/app/connectors/core/kafka_consumer.py, services/python/app/connectors/google/gmail/core/gmail_user_service.py, services/python/app/connectors/google/gmail/core/sync_service.py, services/python/app/connectors/google/gmail/handlers/change_handler.py, services/python/app/connectors/google/google_drive/core/drive_user_service.py, services/python/app/connectors/utils/decorators.py, services/python/app/events/processor.py, services/python/app/modules/indexing/run.py, services/python/app/modules/parsers/google_files/parser_user_service.py, services/python/app/modules/retrieval/retrieval_service.py
Token refresh removed for enterprise. Bounding boxes part of metadata, preprocess_query includes embedding model check, gmail senders receivers logic fixed to handle multiple receivers, gmail webhook and changes logic fixed
=> token refresh, bounding box, gmail permissions, gmail webhook

services/python/app/connectors/google/gmail/core/sync_service.py, services/python/app/connectors/google/google_drive/core/sync_service.py
Added checks for empty token/channel history (drive and gmail respectively.)
=> Empty token/channelHistory handling.

services/python/app/config/configuration_service.py, services/python/app/config/encryption/encryption_service.py, services/python/app/tests/testing_sha256.py
- Created a hashed digest and hexed it.
- using the hexed value as new secret key for encryption-decryption.
- passing the logger from configuration service to encryption service.
=> secret key hash

services/python/app/config/configuration_service.py, services/python/app/connectors/google/gmail/core/gmail_user_service.py, services/python/app/connectors/google/gmail/core/sync_service.py, services/python/app/connectors/google/gmail/handlers/change_handler.py, services/python/app/connectors/google/google_drive/core/drive_user_service.py, services/python/app/modules/extraction/domain_extraction.py, services/python/app/modules/parsers/pdf/ocr_handler.py, services/python/app/modules/retrieval/retrieval_arango.py
- Summary storage now supports both local and s3, azure by using different upload apis for each.
- also handled summary key for etcd in python
- Fixed Gmail webhook processing to handle attachment permissions properly. 
- trashed files logic improved.
=> summary storage changes, gmail attachment changes

services/python/app/api/routes/health.py, services/python/app/connectors/google/gmail/handlers/webhook_handler.py, services/python/app/connectors_main.py, services/python/app/indexing_main.py, services/python/app/modules/indexing/run.py, services/python/app/modules/retrieval/retrieval_service.py, services/python/app/query_main.py
Moved health check api from indexing service to query service.
=> health check api moved to query service

services/python/app/connectors/google/admin/google_admin_service.py, services/python/app/connectors/google/google_drive/core/drive_sync_service.py, services/python/app/connectors/google/google_drive/handlers/drive_change_handler.py, services/python/app/core/redis_scheduler.py, services/python/app/modules/retrieval/retrieval_service.py, services/python/app/utils/time_conversion.py
- Fix for google internal timestamp (sec to ms)
- Gmail attachment weburl handling.
=> google internal time fix, gmail attachment weburl fix

services/python/app/connectors/google/google_drive/core/drive_user_service.py, services/python/app/core/redis_scheduler.py, services/python/app/modules/retrieval/retrieval_service.py
Indexing fields removed from drive records. 
Search and chat handled for empty results.
=> drive records changes. search and chat for empty results handling.

frontend/src/sections/accountdetails/account-settings/connector/components/google-workspace-config-company-form.tsx, frontend/src/sections/accountdetails/account-settings/services/components/arangodb-config-form.tsx, frontend/src/sections/accountdetails/account-settings/services/components/kafka-config-form.tsx, frontend/src/sections/accountdetails/account-settings/services/components/mongodb-config-form.tsx, frontend/src/sections/accountdetails/account-settings/services/components/qdrant-config-form.tsx, frontend/src/sections/accountdetails/account-settings/services/components/redis-config-form.tsx, frontend/src/sections/accountdetails/account-settings/services/components/storage-service-form.tsx, frontend/src/sections/accountdetails/personal-profile.tsx
removal of all data when file is removed in google workspace business form , disabling changes in external settings , double confirmation while changing email
=> minor changes in external settings

services/python/.gitignore, services/python/app/config/configuration_service.py, services/python/app/config/utils/named_constants/arangodb_constants.py, services/python/app/connectors/api/router.py, services/python/app/connectors/google/admin/google_admin_service.py, services/python/app/connectors/google/core/arango_service.py, services/python/app/connectors/google/core/sync_tasks.py, services/python/app/connectors/google/gcal/core/gcal_sync_service.py, services/python/app/connectors/google/gmail/core/gmail_sync_service.py, services/python/app/connectors/google/gmail/handlers/gmail_change_handler.py, services/python/app/connectors/google/google_drive/core/drive_sync_service.py, services/python/app/connectors/google/google_drive/core/drive_user_service.py, services/python/app/connectors/google/google_drive/handlers/drive_change_handler.py, services/python/app/connectors/google/helpers/google_token_handler.py, services/python/app/core/celery_app.py, services/python/app/core/signed_url.py, services/python/app/events/block_prompts.py, services/python/app/indexing_main.py, services/python/app/modules/extraction/domain_extraction.py, services/python/app/query_main.py, services/python/app/schema/arango/documents.py, services/python/app/setups/connector_setup.py
- Fallback created for endpoints in case it is not in etcd.
- Indexing status for shared files is AUTO_INDEX_OFF
- Watches recreation fix.
=> fixes: baseurl fallback, indexing status for sharedfiles, changes watch fix

services/python/app/connectors/api/router.py, services/python/app/connectors/core/sync_kafka_consumer.py, services/python/app/connectors/google/admin/google_admin_service.py, services/python/app/connectors/google/core/arango_service.py, services/python/app/connectors/google/gcal/core/gcal_user_service.py, services/python/app/connectors/google/gmail/core/gmail_sync_service.py, services/python/app/connectors/google/gmail/core/gmail_user_service.py, services/python/app/connectors/google/google_drive/core/drive_sync_service.py, services/python/app/connectors/google/google_drive/core/drive_user_service.py, services/python/app/modules/parsers/google_files/parser_user_service.py
Mail access fix in enterprise account.
=> mail access fix

frontend/src/sections/accountdetails/account-settings/connector/connector-stats.tsx, services/nodejs/apps/src/modules/knowledge_base/container/kb_container.ts, services/nodejs/apps/src/modules/knowledge_base/controllers/kb_controllers.ts, services/nodejs/apps/src/modules/knowledge_base/routes/kb.routes.ts, services/nodejs/apps/src/modules/knowledge_base/services/kb.relation.service.ts, services/nodejs/apps/src/modules/knowledge_base/services/sync_events.service.ts, services/nodejs/apps/src/modules/knowledge_base/validators/validators.ts
Removed duplicate sync events from record events producer
Added sync events handling in the frontend along with more uniform connector stats card
=> Added kafka events api for sync-events, created new producer for sync events

services/python/app/modules/retrieval/retrieval_service.py
Added webUrl to chat citations
=> webUrl added to citations

services/python/app/api/routes/health.py, services/python/app/config/utils/named_constants/ai_models_named_constants.py, services/python/app/modules/indexing/run.py, services/python/app/modules/retrieval/retrieval_service.py
- Disallowed changing of embedding model after qdrant collection has been created
- Added Provider type Default.
=> health check fix

services/python/app/connectors/google/gmail/core/gmail_sync_service.py, services/python/app/connectors/google/google_drive/core/drive_sync_service.py
=> named constant fix

services/python/app/api/routes/health.py, services/python/app/modules/indexing/run.py, services/python/app/modules/retrieval/retrieval_service.py, services/python/app/setups/indexing_setup.py, services/python/app/setups/query_setup.py
- Allowed embedding change when collection exists but is empty
- modified setups to make client and vector store implementation robust
=> embedding health check fix

services/python/app/config/utils/named_constants/arangodb_constants.py, services/python/app/setups/connector_setup.py
Connectors setup crashing on restart fix (enterprise)
=> connector setup fix

frontend/src/sections/accountdetails/account-settings/connector/components/connectors-list.tsx, services/nodejs/apps/src/modules/tokens_manager/types/connector.types.ts, services/python/app/connectors/api/router.py, services/python/app/setups/connector_setup.py
Fixed credentials object to contain expiry field.
=> credentials fix

.github/workflows/main.yml
Reverts pipeshub-ai/pipeshub-ai#422
=> Revert "disable incremental linting job"

backend/python/app/events/processor.py, backend/python/app/modules/extraction/domain_extraction.py
Gmail message to blocks conversion.
=> gmail to blocks

backend/python/app/api/routes/chatbot.py, backend/python/app/config/constants/arangodb.py, backend/python/app/modules/agents/qna/nodes.py, backend/python/app/modules/retrieval/retrieval_service.py, backend/python/app/modules/transformers/vectorstore.py, backend/python/app/utils/chat_helpers.py, backend/python/app/utils/citations.py, backend/python/app/utils/mimetype_to_extension.py, backend/python/app/utils/streaming.py, frontend/src/sections/knowledgebase/knowledge-base-search.tsx, frontend/src/sections/knowledgebase/knowledge-search.tsx, frontend/src/sections/qna/agents/agent-chat.tsx, frontend/src/sections/qna/chatbot/chat-bot.tsx, frontend/src/sections/qna/chatbot/components/sources-citations.tsx
Fixed:
1. Citations doesn't work some times.
2. Mdx citation render issue in frontend
3. Conversation saving failing in case of md & mdx files
=> bug fixes in indexing, frontend & query pipeline

backend/python/app/events/processor.py, backend/python/app/modules/transformers/document_extraction.py, backend/python/app/utils/converters/docling_doc_to_blocks.py
fixed issue 710. Somehow in mac, docling is unable to get the extension of pdf. Explicitly mentioned it in code.
=> fixed issue 710

backend/python/app/sources/client/airtable/airtable.py, backend/python/app/sources/external/airtable/airtable.py, backend/python/app/sources/external/airtable/example.py, backend/python/code-generator/airtable.py, cspell.json
added airtable client and datasource
=> airtable datasource and client

backend/python/app/sources/client/github/github.py, backend/python/app/sources/external/github/example.py, backend/python/app/sources/external/github/github_.py, backend/python/code-generator/github.py
solves #613
output of example looks like:
=> Added github datasource

backend/nodejs/apps/src/modules/crawling_manager/services/task/crawling_task_service_factory.ts, backend/python/app/connectors/core/base/data_processor/data_source_entities_processor.py, backend/python/app/connectors/core/factory/connector_factory.py, backend/python/app/connectors/services/event_service.py, backend/python/app/connectors/sources/atlassian/confluence_cloud/connector.py, backend/python/app/connectors/sources/atlassian/core/oauth.py, backend/python/app/connectors/sources/atlassian/jira_cloud/connector.py, backend/python/app/connectors/sources/atlassian/jira_cloud/example.py, backend/python/app/models/entities.py
=> Jira connector refactoring

backend/python/app/modules/agents/qna/nodes.py, backend/python/app/utils/citations.py
added logic to handle citations in case of agents
=> citation handling for agent

README.md
=> fixing inconsistency in space in connector images

.github/PULL_REQUEST_TEMPLATE.md
=> updated PULL_REQUEST_TEMPLATE.md

backend/python/app/sources/client/gitlab/gitlab.py, backend/python/app/sources/external/gitlab/example.py, backend/python/app/sources/external/gitlab/gitlab_.py, backend/python/code-generator/gitlab.py, backend/python/pyproject.toml
- Fixes #614 
- Related to #614
Created the example.py file inside app/source/external/gitlab which tests some of the methods of the datasource.
All the tests worked listed in the example file
**Before:**
**After:**
- …
=> added gitlab datasource

README.md
=> Tech stack

backend/nodejs/apps/src/index.ts, backend/nodejs/apps/src/libs/middlewares/error.middleware.ts, backend/nodejs/apps/src/libs/utils/error.middleware.utils.ts, backend/python/app/connectors/api/router.py
=> robust global error handler

backend/python/app/connectors/api/router.py
=> remove testing logs and exception

backend/python/app/sources/client/bookstack/bookstack.py, backend/python/app/sources/external/bookstack/bookstack.py, backend/python/app/sources/external/bookstack/example.py, backend/python/code-generator/bookstack.py
=> bookstack datasource & client

backend/python/app/connectors/sources/microsoft/onedrive/connector.py, backend/python/app/connectors/sources/microsoft/sharepoint_online/connector.py, backend/python/app/events/processor.py
=> Fix mime type issue

Dockerfile
=> Add support for PM

backend/python/app/sources/client/http/http_client.py, backend/python/app/sources/client/servicenow/servicenow.py, backend/python/app/sources/external/servicenow/example.py, backend/python/app/sources/external/servicenow/servicenow.py, backend/python/code-generator/servicenow/now_email_api_v1_spec.yaml, backend/python/code-generator/servicenow/now_table_api_latest_spec.yaml, backend/python/code-generator/servicenow/now_table_batch_api_latest_spec.yaml, backend/python/code-generator/servicenow/servicenow.py, cspell.json
=> servicenow client updated & datasource added

README.md
=> docker pulls badge added in README

README.md
=> added star badge

backend/python/app/connectors/api/router.py, backend/python/app/connectors/core/registry/connector_registry.py, backend/python/app/schema/arango/documents.py, frontend/src/sections/accountdetails/connectors/hooks/use-connector-manager.ts
=> Oauth authentication bug fixed

backend/python/app/modules/retrieval/retrieval_service.py, backend/python/app/utils/chat_helpers.py, frontend/src/sections/knowledgebase/knowledge-base-search.tsx, frontend/src/sections/knowledgebase/knowledge-search.tsx, frontend/src/sections/knowledgebase/types/search-response.ts
=> Fixed knowledge search retrival bug
